apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multicluster-mesh-addon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multicluster-mesh-addon
subjects:
- kind: ServiceAccount
  name: multicluster-mesh-addon
  namespace: open-cluster-management
